vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    mappings:
        performance:
            uri_prefix: /uploads/performance
            upload_destination: '%kernel.project_dir%/public/uploads/performance'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            delete_on_update: true
            delete_on_remove: true